version: build {build}

image:
  - Ubuntu

build:
  verbosity: minimal

branches:
  except:
    - gh-pages
skip_tags: true

init:
  - sudo apt update && sudo apt-get install -y dotnet-sdk-5.0
  - git config --global core.autocrlf input

before_build:
  - dotnet tool restore
  - export SEMVER="$(dotnet nbgv get-version -v SemVer2)"
  - dotnet nbgv cloud

build_script:
  - export NUGET_PACKAGES="$APPVEYOR_BUILD_FOLDER/.nuget"
  - ./build.sh -t pack -c Release -v "$SEMVER" --sourceLink /p:GhPages=true

test_script:
  - ./build.sh -s -t test -c Release --push-tests "https://ci.appveyor.com/api/testresults/mstest/$APPVEYOR_JOB_ID"

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL

# all builds on the AppVeyor NuGet feed
artifacts:
  - path: build/*.nupkg
    name: nuget

cache:
  - .nuget
