version: build {build}

image:
- Visual Studio 2017
# - Ubuntu

build:
  verbosity: minimal

branches:
  except:
  - gh-pages
skip_tags: true

init:
- cmd: choco install dotnetcore-sdk --version 3.0.100-preview9-014004
- git config --global core.autocrlf input

before_build:
- ps: |
    dotnet tool install nbgv --tool-path .paket
    $env:SEMVER = .paket/nbgv get-version -v SemVer2
    Update-AppveyorBuild -Version "$env:SEMVER ($env:APPVEYOR_BUILD_ID)"

build_script:
- sh: BUILD_SCRIPT=./build.sh   # Use build.cmd on Windows, build.sh on Linux
- ps: $env:NUGET_PACKAGES = "$env:APPVEYOR_BUILD_FOLDER\.nuget"
  # Chrome on AV is not latest
- ps: |
    dotnet tool install paket --tool-path .paket
    .paket/paket add Selenium.WebDriver.ChromeDriver --version 75.0.3770.140
    dotnet restore
- ps: '& $env:BUILD_SCRIPT -t pack -c Release -v "$env:SEMVER" --sourceLink /p:GhPages=true'

test_script:
- ps: '& $env:BUILD_SCRIPT -s -t test -c Release --push-tests "https://ci.appveyor.com/api/testresults/mstest/$env:APPVEYOR_JOB_ID"'

environment:
  BUILD_SCRIPT: ./build.cmd
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL

# all builds on the AppVeyor NuGet feed
artifacts:
  - path: build\*.nupkg
    name: nuget

for:

# Publish pages to github.io only from master
- branches:
    only:
    - master
  on_success:
  - ps: .\tools\gh-pages.ps1 -env appveyor

# Only use cache on Windows build
# (AV caches for each matrix item separately, and the cache is too large)
# - matrix:
#     only:
#     - image: Visual Studio 2017
#   cache:
#   - .nuget
cache:
- .nuget
