version: 0.1.{build}
image:
- Visual Studio 2017
# - Ubuntu

build:
  verbosity: minimal

branches:
  except:
  - gh-pages

init:
- git config --global core.autocrlf input

build_script:
- sh: BUILD_SCRIPT=./build.sh   # Use build.cmd on Windows, build.sh on Linux
- ps: $env:NUGET_PACKAGES = "$env:APPVEYOR_BUILD_FOLDER\.nuget"
- ps: '& $env:BUILD_SCRIPT -t pack -c Release -v "$env:APPVEYOR_BUILD_VERSION" /p:GhPages=true'

test_script:
- ps: '& $env:BUILD_SCRIPT -s -t test -c Release --push-tests "https://ci.appveyor.com/api/testresults/mstest/$env:APPVEYOR_JOB_ID"'

environment:
  BUILD_SCRIPT: ./build.cmd
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL

nuget:
  disable_publish_on_pr: true

for:

# Publish to NuGet and github.io only from Windows on master
- branches:
    only:
    - master
  # matrix:
  #   only:
  #   - image: Visual Studio 2017
  artifacts:
  - path: build\*.nupkg
    name: nuget
  on_success:
  - ps: .\tools\gh-pages.ps1 -env appveyor

# Only use cache on Windows build
# (AV caches for each matrix item separately, and the cache is too large)
# - matrix:
#     only:
#     - image: Visual Studio 2017
#   cache:
#   - .nuget
cache:
- .nuget
